spring:
  security:
    user:
      name: admin
      password: "{noop}123"
      roles: ADMIN

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username:  ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  thymeleaf:
    cache: false
springdoc:
  show-login-endpoint: true
server:
  port: 8081
