spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username:  ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      schema: "shoppingsite"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: shoppingsite

  thymeleaf:
    cache: false

  liquibase:
    change-log: liquibase/change-log-master.yaml

springdoc:
  show-login-endpoint: true
server:
  port: 8081
